version: '2'
services:
    db_odoo12:
        image: postgres:9.6.9
        container_name: core-12_db
        environment:
            - POSTGRES_USER=odoo12
            - POSTGRES_PASSWORD=odoo12
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - core-12_volume_db:/var/lib/postgresql/data/pgdata
        ports:
            - "5555:5432"
        network_mode: bridge

volumes:
        core-12_volume_db:
                external: true
